# Generated by Django 4.2.10 on 2024-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id_voiture",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("num_matricule", models.CharField(max_length=10)),
                ("marque", models.CharField(max_length=10)),
                ("image", models.CharField(max_length=1000)),
            ],
        ),
    ]
