# Generated by Django 4.2.10 on 2024-04-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Personne", "0001_initial"),
        ("Voiture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture",
            name="id_personne",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="Personne.personnemodels",
            ),
            preserve_default=False,
        ),
    ]
