# Generated by Django 4.2.10 on 2024-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonneModels",
            fields=[
                (
                    "id_personne",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[("masculin", "masculin"), ("feminin", "feminin")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
