# Generated by Django 4.2.10 on 2024-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personne", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id_personne",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[("masculin", "masculin"), ("feminin", "feminin")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
