# Generated by Django 4.2.10 on 2024-04-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Personne", "0002_personne"),
        ("Voiture", "0003_alter_voiture_id_personne"),
    ]

    operations = [
        migrations.DeleteModel(name="PersonneModels",),
    ]
